/**
 * AUTO-GENERATED from tensr-api/app/assistant/capabilities.py
 * via scripts/generate_agent_capabilities_ts.py — DO NOT EDIT.
 *
 * Re-generate: `python tensr-api/scripts/generate_agent_capabilities_ts.py`
 * Drift check: `python tensr-api/scripts/generate_agent_capabilities_ts.py --check`
 */

export const AGENT_AGGREGATES = [
  'count',
  'count_distinct',
  'iqr',
  'max',
  'mean',
  'median',
  'min',
  'mode',
  'percentile',
  'proportion',
  'std',
  'sum',
  'variance',
  'zscore',
] as const;

export const AGENT_CHART_TYPES = ['bar', 'boxplot', 'histogram', 'line', 'scatter'] as const;

export const AGENT_FILTER_OPERATORS = [
  'contains',
  'equals',
  'greaterThan',
  'greaterThanOrEqual',
  'lessThan',
  'lessThanOrEqual',
  'notContains',
  'notEquals',
] as const;

export const AGENT_FIDELITY_IDS = [
  'percentile',
  'iqr',
  'mode',
  'variance',
  'std',
  'boxplot',
  'violin',
  'not_equal',
  'distinct',
  'proportion',
  'z_score',
] as const;

export const AGENT_CAPABILITY_CATALOG = {
  aggregate_aliases: {
    average: 'mean',
    avg: 'mean',
    count: 'count',
    count_distinct: 'count_distinct',
    distinct: 'count_distinct',
    interquartile_range: 'iqr',
    iqr: 'iqr',
    max: 'max',
    maximum: 'max',
    mean: 'mean',
    median: 'median',
    min: 'min',
    minimum: 'min',
    mode: 'mode',
    n: 'count',
    n_distinct: 'count_distinct',
    nunique: 'count_distinct',
    pct: 'percentile',
    pct_of_total: 'proportion',
    percent: 'proportion',
    percentile: 'percentile',
    proportion: 'proportion',
    quantile: 'percentile',
    sd: 'std',
    standard_deviation: 'std',
    standardise: 'zscore',
    standardize: 'zscore',
    std: 'std',
    std_dev: 'std',
    stddev: 'std',
    sum: 'sum',
    total: 'sum',
    unique: 'count_distinct',
    var: 'variance',
    variance: 'variance',
    z_score: 'zscore',
    z_scores: 'zscore',
    zscore: 'zscore',
    zscores: 'zscore',
  },
  aggregates: [
    'count',
    'count_distinct',
    'iqr',
    'max',
    'mean',
    'median',
    'min',
    'mode',
    'percentile',
    'proportion',
    'std',
    'sum',
    'variance',
    'zscore',
  ],
  chart_aliases: {
    bar: 'bar',
    bar_chart: 'bar',
    box: 'boxplot',
    box_plot: 'boxplot',
    boxplot: 'boxplot',
    column: 'bar',
    hist: 'histogram',
    histogram: 'histogram',
    line: 'line',
    line_chart: 'line',
    scatter: 'scatter',
    scatter_plot: 'scatter',
    scatterplot: 'scatter',
  },
  chart_closest: {
    density: 'histogram',
    donut: 'bar',
    kde: 'histogram',
    pie: 'bar',
    violin: 'boxplot',
    violin_plot: 'boxplot',
    violinplot: 'boxplot',
  },
  charts: ['bar', 'boxplot', 'histogram', 'line', 'scatter'],
  fidelity_ids: [
    'percentile',
    'iqr',
    'mode',
    'variance',
    'std',
    'boxplot',
    'violin',
    'not_equal',
    'distinct',
    'proportion',
    'z_score',
  ],
  filter_aliases: {
    '!=': 'notEquals',
    '<': 'lessThan',
    '<=': 'lessThanOrEqual',
    '<>': 'notEquals',
    '=': 'equals',
    '==': 'equals',
    '>': 'greaterThan',
    '>=': 'greaterThanOrEqual',
    contains: 'contains',
    eq: 'equals',
    equal: 'equals',
    equals: 'equals',
    greater_than: 'greaterThan',
    greater_than_or_equal: 'greaterThanOrEqual',
    greaterthan: 'greaterThan',
    greaterthanorequal: 'greaterThanOrEqual',
    gt: 'greaterThan',
    gte: 'greaterThanOrEqual',
    less_than: 'lessThan',
    less_than_or_equal: 'lessThanOrEqual',
    lessthan: 'lessThan',
    lessthanorequal: 'lessThanOrEqual',
    lt: 'lessThan',
    lte: 'lessThanOrEqual',
    ne: 'notEquals',
    not_contains: 'notContains',
    not_equals: 'notEquals',
    notcontains: 'notContains',
    notequal: 'notEquals',
    notequals: 'notEquals',
    '\u2260': 'notEquals',
  },
  filter_operators: [
    'contains',
    'equals',
    'greaterThan',
    'greaterThanOrEqual',
    'lessThan',
    'lessThanOrEqual',
    'notContains',
    'notEquals',
  ],
} as const;
