import { JSX, ReactNode } from 'react';
import {
  LuCalculator,
  LuDatabase,
  LuFilter,
  LuChartLine,
  LuTableProperties,
  LuWrench,
  LuBlocks,
  LuFileText,
  LuBrain,
  LuTrendingUp,
  LuChartBar,
  LuChartArea,
  LuChartScatter,
  LuActivity,
  LuZap,
  LuCode,
  LuSettings,
} from 'react-icons/lu';
import { FilePickerWrapper } from '@/components/molecules/file-picker';
import {
  Mean,
  OneWayAnova,
  OneSampleTTest,
  Correlation,
  LinearRegression,
  ChiSquare,
  FactorAnalysis,
  DataVisualization,
  DescriptiveStatistics,
  Clustering,
  TimeSeries,
} from '@/components/templates/analysis';
import { SEM } from '@/components/templates/analysis/sem';
import { ExportDialog, MergeDatasetDialog } from '@/components/templates/data';
import FindDuplicatesDialog from '@/components/templates/data/find-duplicates';
import { HandleMissingDataDialog } from '@/components/templates/data/handle-missing-data';
import { FixDataTypesDialog } from '@/components/templates/data/fix-data-types';
import StandardizeValuesDialog from '@/components/templates/data/standardise-values';
import DataQualityDialog from '@/components/templates/data/data-quality';
import ComputeVariablesDialog from '@/components/templates/transform/compute-variable';
import CountValuesDialog from '@/components/templates/transform/count-values';
import ShiftValuesDialog from '@/components/templates/transform/shift-values';
import { MessageCircle } from 'lucide-react';

export type MenuSection = Record<string, string[]>;

export interface MenuItem {
  icon: ReactNode;
  sections: MenuSection;
}

export type MenuItems = Record<string, MenuItem>;

export type AnalysisComponent = ({ children }: { children: ReactNode }) => JSX.Element | null;

export const ANALYSIS_COMPONENTS: Record<string, AnalysisComponent> = {
  // Descriptive Statistics
  'Compare Means': Mean,
  'One Way Anova': OneWayAnova,
  'One Sample T-Test': OneSampleTTest,
  'Descriptive Statistics': DescriptiveStatistics,
  Frequencies: DescriptiveStatistics,
  Descriptives: DescriptiveStatistics,
  Crosstabs: DescriptiveStatistics,
  Explore: DescriptiveStatistics,
  'Ratio Statistics': DescriptiveStatistics,
  'Custom Tables': DescriptiveStatistics,
  'Pivot Tables': DescriptiveStatistics,

  // Correlation & Regression
  'Correlation Analysis': Correlation,
  'Linear Regression': LinearRegression,
  'Partial Correlation': Correlation,
  'Multiple Regression': LinearRegression,
  'Logistic Regression': LinearRegression,
  'Polynomial Regression': LinearRegression,
  'Stepwise Regression': LinearRegression,
  'Poisson Regression': LinearRegression,
  'Probit Regression': LinearRegression,

  // Non-parametric Tests
  'Chi-Square Test': ChiSquare,
  'Mann-Whitney U': ChiSquare,
  'Wilcoxon Signed-Rank': ChiSquare,
  'Kruskal-Wallis H': ChiSquare,
  'Friedman Test': ChiSquare,
  'Sign Test': ChiSquare,
  'Runs Test': ChiSquare,
  'Kolmogorov-Smirnov': ChiSquare,

  // Advanced Analytics
  'Factor Analysis': FactorAnalysis,
  PCA: FactorAnalysis,
  EFA: FactorAnalysis,
  'Reliability Analysis': FactorAnalysis,
  'Cluster Analysis': Clustering,
  'Discriminant Analysis': Clustering,
  'Multidimensional Scaling': Clustering,
  'Correspondence Analysis': Clustering,
  'Survival Analysis': TimeSeries,
  'Time Series Analysis': TimeSeries,
  'Mixed Models': TimeSeries,
  'Hierarchical Linear Modeling': TimeSeries,
  'Structural Equation Modeling': SEM,
  'Path Analysis': SEM,
  'Confirmatory Factor Analysis': SEM,

  // Machine Learning
  Classification: Clustering,
  Regression: LinearRegression,
  'Ensemble Methods': Clustering,
  'Support Vector Machines': Clustering,
  'Neural Networks': Clustering,
  'Decision Trees': Clustering,
  'Random Forest': Clustering,
  'Gradient Boosting': Clustering,
  'Dimensionality Reduction': FactorAnalysis,
  'Association Rules': Clustering,
  'Anomaly Detection': Clustering,
  'Topic Modeling': Clustering,
  'Market Basket Analysis': Clustering,
  'Model Selection': Clustering,
  'Hyperparameter Tuning': Clustering,
  'Cross-validation': Clustering,
  'Model Evaluation': Clustering,
  'Model Deployment': Clustering,
  'A/B Testing': Clustering,

  // Data Visualization
  'Data Visualization': DataVisualization,
  'Bar Charts': DataVisualization,
  'Pie Charts': DataVisualization,
  'Line Charts': DataVisualization,
  'Area Charts': DataVisualization,
  'Dot Plots': DataVisualization,
  Histograms: DataVisualization,
  Boxplots: DataVisualization,
  'Violin Plots': DataVisualization,
  Scatterplots: DataVisualization,
  '3D Scatterplots': DataVisualization,
  'Density Plots': DataVisualization,
  'Frequency Polygons': DataVisualization,
  'Error Bars': DataVisualization,
  'Time Series Plots': DataVisualization,
  'Control Charts': DataVisualization,
  'Survival Curves': DataVisualization,
  'ROC Curves': DataVisualization,
  'Q-Q Plots': DataVisualization,
  'P-P Plots': DataVisualization,

  // Data Operations
  'Import Data': FilePickerWrapper,
  'Export Data': ExportDialog,
  'Merge Datasets': MergeDatasetDialog,
  'Find Duplicates': FindDuplicatesDialog,
  'Handle Missing Data': HandleMissingDataDialog,
  'Fix Data Types': FixDataTypesDialog,
  'Standardize Values': StandardizeValuesDialog,
  'Data Quality Report': DataQualityDialog,
  'Compute Variable': ComputeVariablesDialog,
  'Count Values': CountValuesDialog,
  'Shift Values': ShiftValuesDialog,

  // Transform Operations
  'Create Dummy Variables': ComputeVariablesDialog,
  'Create New Variables': ComputeVariablesDialog,
  'Reshape Data': ComputeVariablesDialog,
  'Aggregate Data': ComputeVariablesDialog,
  'Transpose Data': ComputeVariablesDialog,
  'Sample Data': ComputeVariablesDialog,
  'Feature Engineering': ComputeVariablesDialog,
  'String Functions': ComputeVariablesDialog,
  'Date/Time Functions': ComputeVariablesDialog,
  'Weight Cases': ComputeVariablesDialog,
  'Split Files': ComputeVariablesDialog,
  'Propensity Matching': ComputeVariablesDialog,
  'Case Control Matching': ComputeVariablesDialog,
  'Rake Weights': ComputeVariablesDialog,
  'Text Processing': ComputeVariablesDialog,
  'Conditional Logic': ComputeVariablesDialog,
  'Rank Cases': ComputeVariablesDialog,
  'Percentile Calculations': ComputeVariablesDialog,
  'Recode Variables': ComputeVariablesDialog,
  'Automatic Recode': ComputeVariablesDialog,
  'Extended Recode': ComputeVariablesDialog,
  'Visual Binning': ComputeVariablesDialog,
  'Standardize Variables': StandardizeValuesDialog,
  'Random Number Generator': ComputeVariablesDialog,
  'Create Time Series': TimeSeries,
  'Date and Time Wizard': TimeSeries,
  'Replace Missing Values': HandleMissingDataDialog,
  'Time Intervals': TimeSeries,
  'Seasonal Adjustments': TimeSeries,
  'Restructure Data': ComputeVariablesDialog,
  'Stack/Unstack': ComputeVariablesDialog,
  'Split/Combine': ComputeVariablesDialog,
  'Merge Files': MergeDatasetDialog,
  'Add Cases': MergeDatasetDialog,
  'Add Variables': MergeDatasetDialog,
  'Match Files': MergeDatasetDialog,

  // Syntax & Programming
  'Syntax Editor': DataVisualization,
  'Command Language': DataVisualization,
  Macros: DataVisualization,
  Scripts: DataVisualization,
  'Batch Processing': DataVisualization,
  'Syntax Validation': DataVisualization,
  'Python Integration': DataVisualization,
  'R Integration': DataVisualization,
  'Custom Functions': DataVisualization,
  'API Access': DataVisualization,
  Automation: DataVisualization,
  'Custom Dialogs': DataVisualization,
  'Reproducible Analysis': DataVisualization,
  'Version Control': DataVisualization,
  'Template Creation': DataVisualization,
  'Batch Jobs': DataVisualization,
  'Scheduled Tasks': DataVisualization,

  // Utilities
  'Variable Sets': DataVisualization,
  'Variable Properties': DataVisualization,
  'Variable Groups': DataVisualization,
  'Measurement Levels': DataVisualization,
  'Value Labels': DataVisualization,
  'Table Appearance': DataVisualization,
  'Output Formatting': DataVisualization,
  'Export Settings': ExportDialog,
  'Report Templates': DataVisualization,
  'Automated Reporting': DataVisualization,
  'Interactive Dashboards': DataVisualization,
  'Save Chart Template': DataVisualization,
  'Load Template': DataVisualization,
  'Manage Templates': DataVisualization,
  'Theme Management': DataVisualization,
  'Color Palettes': DataVisualization,
  'Run Script': DataVisualization,
  'Scoring Rules': DataVisualization,
  'Workflow Automation': DataVisualization,
  'Task Scheduling': DataVisualization,
  'Data Comments': DataVisualization,
  'Variable Definitions': DataVisualization,
  'Output Templates': DataVisualization,
  'Analysis Logs': DataVisualization,
  'Audit Trails': DataVisualization,
  'Multi-user Access': DataVisualization,
  'Role-based Permissions': DataVisualization,
  'Sharing Results': DataVisualization,
  'Team Workspaces': DataVisualization,
} as const;

export const MENU_ITEMS: MenuItems = {
  agent: {
    icon: <MessageCircle className="h-4 w-4" />,
    sections: {},
  },
  actions: {
    icon: <LuFilter className="h-4 w-4" />,
    sections: {},
  },
  graph_options: {
    icon: <LuChartLine className="h-4 w-4" />,
    sections: {},
  },
  plugins: {
    icon: <LuBlocks className="h-4 w-4" />,
    sections: {},
  },
  data: {
    icon: <LuDatabase className="h-4 w-4" />,
    sections: {
      'Import & Export': [
        'Import Data',
        'Export Data',
        'Database Connections',
        'Multiple File Formats',
        'Compressed Files',
        'Multi-sheet Excel',
      ],
      'Basic Operations': [
        'Merge Datasets',
        'Data Pipeline',
        'Open Multiple Datasets',
        'Data Versioning',
        'Data Lineage',
      ],
      'Data Cleaning': [
        'Find Duplicates',
        'Handle Missing Data',
        'Fix Data Types',
        'Standardize Values',
        'Data Quality Report',
        'Data Validation Rules',
        'Custom Missing Values',
        'Value Labels',
        'Variable Labels',
      ],
      'Data Management': [
        'Create Variables',
        'Delete Variables',
        'Rename Variables',
        'Variable Properties',
        'Measurement Levels',
        'Multiple Response Sets',
        'Custom Scripts',
        'API Connections',
      ],
    },
  },
  transform: {
    icon: <LuTableProperties className="h-4 w-4" />,
    sections: {
      'Create & Transform': [
        'Compute Variable',
        'Count Values',
        'Shift Values',
        'Create Dummy Variables',
        'Create New Variables',
        'Reshape Data',
        'Aggregate Data',
        'Transpose Data',
        'Sample Data',
        'Feature Engineering',
        'String Functions',
        'Date/Time Functions',
      ],
      'Advanced Transformations': [
        'Weight Cases',
        'Split Files',
        'Propensity Matching',
        'Case Control Matching',
        'Rake Weights',
        'Text Processing',
        'Conditional Logic',
        'Rank Cases',
        'Percentile Calculations',
      ],
      'Recode & Binning': [
        'Recode Variables',
        'Automatic Recode',
        'Extended Recode',
        'Visual Binning',
        'Standardize Variables',
        'Random Number Generator',
      ],
      'Time Series': [
        'Create Time Series',
        'Date and Time Wizard',
        'Replace Missing Values',
        'Time Intervals',
        'Seasonal Adjustments',
      ],
      'Data Preparation': [
        'Restructure Data',
        'Stack/Unstack',
        'Split/Combine',
        'Merge Files',
        'Add Cases',
        'Add Variables',
        'Match Files',
      ],
    },
  },
  analyze: {
    icon: <LuCalculator className="h-4 w-4" />,
    sections: {
      'Descriptive Statistics': [
        'Compare Means',
        'Compare Subgroups',
        'One Sample T-Test',
        'Independent Samples T-Test',
        'Paired Samples T-Test',
        'One Way Anova',
        'Factorial ANOVA',
        'Repeated Measures ANOVA',
        'MANOVA',
        'MANCOVA',
        'Frequencies',
        'Descriptives',
        'Crosstabs',
        'Explore',
        'Ratio Statistics',
        'Custom Tables',
        'Pivot Tables',
      ],
      'Correlation & Regression': [
        'Correlation Analysis',
        'Partial Correlation',
        'Linear Regression',
        'Multiple Regression',
        'Logistic Regression',
        'Polynomial Regression',
        'Stepwise Regression',
        'Poisson Regression',
        'Probit Regression',
        'Point-biserial',
        'Phi Coefficient',
      ],
      'Non-parametric Tests': [
        'Chi-Square Test',
        'Mann-Whitney U',
        'Wilcoxon Signed-Rank',
        'Kruskal-Wallis H',
        'Friedman Test',
        'Sign Test',
        'Runs Test',
        'Kolmogorov-Smirnov',
      ],
      'Advanced Analytics': [
        'Factor Analysis',
        'PCA',
        'EFA',
        'Reliability Analysis',
        'Cluster Analysis',
        'Discriminant Analysis',
        'Multidimensional Scaling',
        'Correspondence Analysis',
        'Survival Analysis',
        'Time Series Analysis',
        'Mixed Models',
        'Hierarchical Linear Modeling',
      ],
      'Machine Learning': [
        'Decision Trees',
        'Random Forest',
        'Neural Networks',
        'Support Vector Machines',
        'Model Selection',
        'Hyperparameter Tuning',
        'Cross-validation',
        'Feature Selection',
      ],
      'Quality Control': [
        'Process Capability',
        'Control Charts',
        'Design of Experiments',
        'Response Surface Methodology',
        'Statistical Process Control',
      ],
    },
  },
  visualization: {
    icon: <LuChartBar className="h-4 w-4" />,
    sections: {
      'Basic Charts': ['Bar Charts', 'Pie Charts', 'Line Charts', 'Area Charts', 'Dot Plots'],
      'Statistical Plots': [
        'Histograms',
        'Boxplots',
        'Violin Plots',
        'Scatterplots',
        '3D Scatterplots',
        'Density Plots',
        'Frequency Polygons',
        'Error Bars',
      ],
      'Specialized Plots': [
        'Time Series Plots',
        'Control Charts',
        'Survival Curves',
        'ROC Curves',
        'Q-Q Plots',
        'P-P Plots',
      ],
      'Chart Features': [
        'Chart Templates',
        'Interactive Editing',
        'Multiple Overlays',
        'Color Schemes',
        'Custom Formatting',
        'Chart Builder',
      ],
    },
  },
  time_series: {
    icon: <LuTrendingUp className="h-4 w-4" />,
    sections: {
      'Time Series Analysis': [
        'ARIMA Models',
        'Exponential Smoothing',
        'Seasonal Decomposition',
        'Autocorrelation',
        'Partial Autocorrelation',
        'Forecasting',
        'Trend Analysis',
        'Seasonality Detection',
      ],
      'Advanced Time Series': [
        'VAR Models',
        'GARCH Models',
        'State Space Models',
        'Intervention Analysis',
        'Transfer Functions',
        'Spectral Analysis',
      ],
    },
  },
  ml_ai: {
    icon: <LuBrain className="h-4 w-4" />,
    sections: {
      'Supervised Learning': [
        'Classification',
        'Regression',
        'Ensemble Methods',
        'Support Vector Machines',
        'Neural Networks',
        'Decision Trees',
        'Random Forest',
        'Gradient Boosting',
      ],
      'Unsupervised Learning': [
        'Clustering',
        'Dimensionality Reduction',
        'Association Rules',
        'Anomaly Detection',
        'Topic Modeling',
        'Market Basket Analysis',
      ],
      'Model Management': [
        'Model Selection',
        'Hyperparameter Tuning',
        'Cross-validation',
        'Feature Engineering',
        'Model Evaluation',
        'Model Deployment',
        'A/B Testing',
      ],
    },
  },
  syntax: {
    icon: <LuCode className="h-4 w-4" />,
    sections: {
      'SPSS Syntax': [
        'Syntax Editor',
        'Command Language',
        'Macros',
        'Scripts',
        'Batch Processing',
        'Syntax Validation',
      ],
      Programming: [
        'Python Integration',
        'R Integration',
        'Custom Functions',
        'API Access',
        'Automation',
        'Custom Dialogs',
      ],
      Workflow: [
        'Reproducible Analysis',
        'Version Control',
        'Template Creation',
        'Batch Jobs',
        'Scheduled Tasks',
      ],
    },
  },
  utilities: {
    icon: <LuWrench className="h-4 w-4" />,
    sections: {
      'Variable Management': [
        'Variable Sets',
        'Variable Properties',
        'Variable Groups',
        'Measurement Levels',
        'Value Labels',
        'Missing Values',
      ],
      'Output Options': [
        'Table Appearance',
        'Output Formatting',
        'Export Settings',
        'Report Templates',
        'Automated Reporting',
        'Interactive Dashboards',
      ],
      'Chart Templates': [
        'Save Chart Template',
        'Load Template',
        'Manage Templates',
        'Theme Management',
        'Color Palettes',
      ],
      Automation: [
        'Run Script',
        'Batch Processing',
        'Scoring Rules',
        'Workflow Automation',
        'Task Scheduling',
      ],
      Documentation: [
        'Data Comments',
        'Variable Definitions',
        'Output Templates',
        'Analysis Logs',
        'Audit Trails',
      ],
      Collaboration: [
        'Multi-user Access',
        'Role-based Permissions',
        'Version Control',
        'Sharing Results',
        'Team Workspaces',
      ],
    },
  },
} as const;
