import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { TabsProvider } from '@/contexts/tabs-context';
import { ProjectProvider } from '@/contexts/project-context';
import { SidebarProvider } from '@/components/organisms/sidebar';
import { AuthProvider } from '@/contexts/auth-context';
import { AppProvider } from '@/contexts/app-context';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <AppProvider>
          <ProjectProvider>
            <AuthProvider>
              <TabsProvider>
                <SidebarProvider>{children}</SidebarProvider>
              </TabsProvider>
            </AuthProvider>
          </ProjectProvider>
        </AppProvider>
      </body>
    </html>
  );
}
